/**
 * OPM Occupational Groups and Families with their associated Series
 * Based on OPM's Handbook of Occupational Groups and Families
 */

export interface OccupationalSeries {
  code: string;
  title: string;
}

export interface OccupationalGroup {
  code: string;
  title: string;
  series: OccupationalSeries[];
}

export const OPM_OCCUPATIONAL_GROUPS: OccupationalGroup[] = [
  {
    code: '0000',
    title: 'Miscellaneous Occupations Group',
    series: [
      { code: '0006', title: 'Correctional Institution Administration' },
      { code: '0007', title: 'Correctional Officer' },
      { code: '0011', title: 'Bond Sales Promotion' },
      { code: '0018', title: 'Safety and Occupational Health Management' },
      { code: '0019', title: 'Safety Technician' },
      { code: '0020', title: 'Community Planning' },
      { code: '0021', title: 'Community Planning Technician' },
      { code: '0023', title: 'Outdoor Recreation Planning' },
      { code: '0025', title: 'Park Ranger' },
      { code: '0028', title: 'Environmental Protection Specialist' },
      { code: '0029', title: 'Environmental Protection Assistant' },
      { code: '0030', title: 'Sports Specialist' },
      { code: '0050', title: 'Funeral Directing' },
      { code: '0060', title: 'Chaplain' },
      { code: '0062', title: 'Clothing Design' },
      { code: '0072', title: 'Fingerprint Identification' },
      { code: '0080', title: 'Security Administration' },
      { code: '0081', title: 'Fire Protection and Prevention' },
      { code: '0082', title: 'United States Marshal' },
      { code: '0083', title: 'Police' },
      { code: '0084', title: 'Nuclear Materials Courier' },
      { code: '0085', title: 'Security Guard' },
      { code: '0086', title: 'Security Clerical and Assistance' },
      { code: '0090', title: 'Guide' },
      { code: '0095', title: 'Foreign Law Specialist' },
      { code: '0099', title: 'General Student Trainee' },
    ],
  },
  {
    code: '0100',
    title: 'Social Science, Psychology, and Welfare Group',
    series: [
      { code: '0101', title: 'Social Science' },
      { code: '0102', title: 'Social Science Aid and Technician' },
      { code: '0105', title: 'Social Insurance Administration' },
      { code: '0106', title: 'Unemployment Insurance' },
      { code: '0110', title: 'Economist' },
      { code: '0119', title: 'Economics Assistant' },
      { code: '0130', title: 'Foreign Affairs' },
      { code: '0131', title: 'International Relations' },
      { code: '0132', title: 'Intelligence' },
      { code: '0135', title: 'Foreign Agricultural Affairs' },
      { code: '0136', title: 'International Cooperation' },
      { code: '0140', title: 'Manpower Research and Analysis' },
      { code: '0150', title: 'Geography' },
      { code: '0151', title: 'Geography Aid and Technician' },
      { code: '0160', title: 'Civil Rights Analysis' },
      { code: '0170', title: 'History' },
      { code: '0180', title: 'Psychology' },
      { code: '0181', title: 'Psychology Aid and Technician' },
      { code: '0184', title: 'Sociology' },
      { code: '0185', title: 'Social Work' },
      { code: '0186', title: 'Social Services Aid and Assistant' },
      { code: '0187', title: 'Social Services' },
      { code: '0188', title: 'Recreation Specialist' },
      { code: '0189', title: 'Recreation Aid and Assistant' },
      { code: '0190', title: 'General Anthropology' },
      { code: '0191', title: 'Archeology' },
      { code: '0193', title: 'History Technician' },
      { code: '0199', title: 'Social Science Student Trainee' },
    ],
  },
  {
    code: '0200',
    title: 'Personnel Management and Industrial Relations Group',
    series: [
      { code: '0201', title: 'Personnel Management' },
      { code: '0203', title: 'Human Resources Management' },
      { code: '0204', title: 'Military Personnel Management' },
      { code: '0205', title: 'Military Personnel Clerical and Technician' },
      { code: '0210', title: 'Transportation Specialist' },
      { code: '0212', title: 'Personnel Staffing' },
      { code: '0213', title: 'Personnel Clerical and Assistance' },
      { code: '0241', title: 'Mediation' },
      { code: '0243', title: 'Apprenticeship and Training' },
      { code: '0244', title: 'Labor-Management Relations Examining' },
      { code: '0249', title: 'Personnel Management Student Trainee' },
    ],
  },
  {
    code: '0300',
    title: 'General Administrative, Clerical, and Office Services Group',
    series: [
      { code: '0301', title: 'Miscellaneous Administration and Program' },
      { code: '0302', title: 'Miscellaneous Clerk and Assistant' },
      { code: '0303', title: 'Miscellaneous Clerk and Typist' },
      { code: '0304', title: 'Information Receptionist' },
      { code: '0305', title: 'Mail and File' },
      { code: '0306', title: 'Office Automation Clerical and Assistance' },
      { code: '0308', title: 'Records Administration' },
      { code: '0309', title: 'Correspondence Clerk' },
      { code: '0311', title: 'Miscellaneous Administrative Support' },
      { code: '0318', title: 'Secretary' },
      { code: '0319', title: 'Closed Microphone Reporting' },
      { code: '0322', title: 'Clerk-Stenographer and Reporter' },
      { code: '0326', title: 'Office Automation Clerical' },
      { code: '0332', title: 'Computer Operation' },
      { code: '0334', title: 'Computer Clerk and Assistant' },
      { code: '0335', title: 'Computer Assistant' },
      { code: '0340', title: 'Program Management' },
      { code: '0341', title: 'Administrative Officer' },
      { code: '0342', title: 'Support Services Administration' },
      { code: '0343', title: 'Management and Program Analysis' },
      { code: '0344', title: 'Management and Program Clerical and Assistance' },
      { code: '0346', title: 'Logistics Management' },
      { code: '0350', title: 'Equipment Operator' },
      { code: '0351', title: 'General Services' },
      { code: '0356', title: 'Data Transcriber' },
      { code: '0357', title: 'Coding' },
      { code: '0359', title: 'Schedules' },
      { code: '0360', title: 'Equal Employment Opportunity' },
      { code: '0361', title: 'Equal Opportunity Assistance' },
      { code: '0362', title: 'Contact Representative' },
      { code: '0365', title: 'Social Insurance Claims Examining' },
      { code: '0367', title: 'Contact Representative (Claims Examining)' },
      { code: '0368', title: 'Social Insurance Representative' },
      { code: '0369', title: 'Medicare Representative' },
      { code: '0382', title: 'Telephone Operating' },
      { code: '0383', title: 'Telecommunications Processing' },
      { code: '0384', title: 'Telecommunications Mechanic' },
      { code: '0391', title: 'Telecommunication' },
      { code: '0392', title: 'General Telecommunications' },
      { code: '0399', title: 'Administration and Office Support Student Trainee' },
    ],
  },
  {
    code: '0400',
    title: 'Natural Resources Management and Biological Sciences Group',
    series: [
      { code: '0401', title: 'General Natural Resources Management and Biological Sciences' },
      { code: '0403', title: 'Microbiology' },
      { code: '0404', title: 'Biological Science Technician' },
      { code: '0405', title: 'Pharmacology' },
      { code: '0408', title: 'Ecology' },
      { code: '0409', title: 'Botany' },
      { code: '0410', title: 'Zoology' },
      { code: '0413', title: 'Physiology' },
      { code: '0414', title: 'Entomology' },
      { code: '0415', title: 'Toxicology' },
      { code: '0421', title: 'Plant Protection Technician' },
      { code: '0430', title: 'Forestry' },
      { code: '0431', title: 'Forestry Technician' },
      { code: '0434', title: 'Forest Products Technology' },
      { code: '0435', title: 'Soil Conservation' },
      { code: '0436', title: 'Soil Conservation Technician' },
      { code: '0437', title: 'Soil Science' },
      { code: '0440', title: 'Genetics' },
      { code: '0454', title: 'Rangeland Management' },
      { code: '0455', title: 'Range Technician' },
      { code: '0457', title: 'Agricultural Extension' },
      { code: '0458', title: 'Agricultural Commodity Warehouse Examining' },
      { code: '0459', title: 'Agricultural Commodity Aid' },
      { code: '0460', title: 'Forestry' },
      { code: '0462', title: 'Fishery Biology' },
      { code: '0463', title: 'Fish and Wildlife Administration' },
      { code: '0464', title: 'Wildlife Biology' },
      { code: '0465', title: 'Wildlife Refuge Management' },
      { code: '0470', title: 'Soil Science' },
      { code: '0471', title: 'Agronomy' },
      { code: '0475', title: 'Range Research' },
      { code: '0477', title: 'Plant Pathology' },
      { code: '0478', title: 'Agricultural Commodity Grading' },
      { code: '0479', title: 'Agricultural Research' },
      { code: '0480', title: 'General Fish and Wildlife Administration' },
      { code: '0482', title: 'Fish Biology' },
      { code: '0485', title: 'Wildlife Refuge Management' },
      { code: '0486', title: 'Wildlife Biology' },
      { code: '0487', title: 'Animal Science' },
      { code: '0488', title: 'Agricultural Extension' },
      { code: '0499', title: 'Biological Science Student Trainee' },
    ],
  },
  {
    code: '0500',
    title: 'Accounting and Budget Group',
    series: [
      { code: '0501', title: 'Financial Administration and Program' },
      { code: '0503', title: 'Financial Clerical and Technician' },
      { code: '0505', title: 'Financial Management' },
      { code: '0510', title: 'Accounting' },
      { code: '0511', title: 'Auditing' },
      { code: '0512', title: 'Internal Revenue Agent' },
      { code: '0513', title: 'Internal Revenue Officer' },
      { code: '0518', title: 'Revenue Agent' },
      { code: '0521', title: 'Accounting Technician' },
      { code: '0525', title: 'Accounting' },
      { code: '0526', title: 'Tax Specialist' },
      { code: '0530', title: 'Cash Processing' },
      { code: '0540', title: 'Voucher Examining' },
      { code: '0544', title: 'Civilian Pay' },
      { code: '0545', title: 'Military Pay' },
      { code: '0560', title: 'Budget Analysis' },
      { code: '0561', title: 'Budget Clerical and Assistance' },
      { code: '0599', title: 'Financial Management Student Trainee' },
    ],
  },
  {
    code: '0600',
    title: 'Medical, Hospital, Dental, and Public Health Group',
    series: [
      { code: '0601', title: 'General Health Science' },
      { code: '0602', title: 'Medical Officer' },
      { code: '0603', title: 'Physician Assistant' },
      { code: '0610', title: 'Nurse' },
      { code: '0620', title: 'Practical Nurse' },
      { code: '0630', title: 'Dietitian and Nutritionist' },
      { code: '0631', title: 'Occupational Therapist' },
      { code: '0633', title: 'Physical Therapist' },
      { code: '0635', title: 'Kinesiotherapy' },
      { code: '0636', title: 'Recreation/Creative Arts Therapist' },
      { code: '0637', title: 'Manual Arts Therapist' },
      { code: '0638', title: 'Recreation/Creative Arts Therapist' },
      { code: '0639', title: 'Educational Therapist' },
      { code: '0640', title: 'Health Aid and Technician' },
      { code: '0642', title: 'Nuclear Medicine Technician' },
      { code: '0644', title: 'Medical Technologist' },
      { code: '0645', title: 'Medical Technician' },
      { code: '0646', title: 'Pathology Technician' },
      { code: '0647', title: 'Diagnostic Radiologic Technologist' },
      { code: '0648', title: 'Therapeutic Radiologic Technologist' },
      { code: '0649', title: 'Medical Instrument Technician' },
      { code: '0651', title: 'Respiratory Therapist' },
      { code: '0653', title: 'EKG Technician' },
      { code: '0655', title: 'Cardiac Catheterization Technician' },
      { code: '0658', title: 'Rehabilitation Therapy Assistant' },
      { code: '0660', title: 'Pharmacist' },
      { code: '0661', title: 'Pharmacy Technician' },
      { code: '0662', title: 'Optometrist' },
      { code: '0665', title: 'Speech Pathology and Audiology' },
      { code: '0667', title: 'Orthotist and Prosthetist' },
      { code: '0668', title: 'Podiatrist' },
      { code: '0669', title: 'Medical Records Administration' },
      { code: '0670', title: 'Health System Administration' },
      { code: '0671', title: 'Health System Specialist' },
      { code: '0672', title: 'Prosthetic Representative' },
      { code: '0673', title: 'Hospital Housekeeping Management' },
      { code: '0675', title: 'Medical Records Technician' },
      { code: '0676', title: 'Medical Support Assistance' },
      { code: '0677', title: 'Medical Clerk' },
      { code: '0679', title: 'Medical Support Assistance' },
      { code: '0680', title: 'Dental Officer' },
      { code: '0681', title: 'Dental Assistant' },
      { code: '0682', title: 'Dental Hygiene' },
      { code: '0683', title: 'Dental Laboratory Aid and Technician' },
      { code: '0685', title: 'Public Health Program Specialist' },
      { code: '0688', title: 'Sanitarian' },
      { code: '0690', title: 'Industrial Hygiene' },
      { code: '0696', title: 'Consumer Safety' },
      { code: '0698', title: 'Environmental Health Technician' },
      { code: '0699', title: 'Medical and Health Student Trainee' },
    ],
  },
  {
    code: '0700',
    title: 'Veterinary Medical Science Group',
    series: [
      { code: '0701', title: 'Veterinary Medical Science' },
      { code: '0704', title: 'Animal Health Technician' },
      { code: '0799', title: 'Veterinary Medical Science Student Trainee' },
    ],
  },
  {
    code: '0800',
    title: 'Engineering and Architecture Group',
    series: [
      { code: '0801', title: 'General Engineering' },
      { code: '0802', title: 'Engineering Technical' },
      { code: '0803', title: 'Safety Engineering' },
      { code: '0804', title: 'Fire Protection Engineering' },
      { code: '0806', title: 'Materials Engineering' },
      { code: '0807', title: 'Landscape Architecture' },
      { code: '0808', title: 'Architecture' },
      { code: '0809', title: 'Construction Control Technical' },
      { code: '0810', title: 'Civil Engineering' },
      { code: '0817', title: 'Survey Technical' },
      { code: '0819', title: 'Environmental Engineering' },
      { code: '0828', title: 'Construction Analyst' },
      { code: '0830', title: 'Mechanical Engineering' },
      { code: '0840', title: 'Nuclear Engineering' },
      { code: '0850', title: 'Electrical Engineering' },
      { code: '0854', title: 'Computer Engineering' },
      { code: '0855', title: 'Electronics Engineering' },
      { code: '0856', title: 'Electronics Technical' },
      { code: '0858', title: 'Biomedical Engineering' },
      { code: '0861', title: 'Aerospace Engineering' },
      { code: '0868', title: 'Marine Survey Technical' },
      { code: '0871', title: 'Naval Architecture' },
      { code: '0873', title: 'Marine Engineering' },
      { code: '0880', title: 'Mining Engineering' },
      { code: '0881', title: 'Petroleum Engineering' },
      { code: '0893', title: 'Chemical Engineering' },
      { code: '0895', title: 'Agricultural Engineering' },
      { code: '0896', title: 'Industrial Engineering' },
      { code: '0899', title: 'Engineering and Architecture Student Trainee' },
    ],
  },
  {
    code: '0900',
    title: 'Legal and Kindred Group',
    series: [
      { code: '0901', title: 'General Legal and Kindred Administration' },
      { code: '0904', title: 'Law Clerk' },
      { code: '0905', title: 'General Attorney' },
      { code: '0906', title: 'General Claims Examining' },
      { code: '0907', title: 'Adjudication' },
      { code: '0910', title: 'Paralegal Specialist' },
      { code: '0915', title: 'Technical Writing and Editing' },
      { code: '0920', title: 'Trade Specialist' },
      { code: '0930', title: 'Hearings and Appeals' },
      { code: '0935', title: 'General Claims Examining' },
      { code: '0945', title: 'General Legal and Kindred Administration' },
      { code: '0950', title: 'Paralegal Specialist' },
      { code: '0955', title: 'Social Insurance Claims Examining' },
      { code: '0958', title: 'Social Insurance Representative' },
      { code: '0962', title: 'Contact Representative' },
      { code: '0963', title: 'Legal Instruments Examining' },
      { code: '0965', title: 'Land Law Examining' },
      { code: '0967', title: 'Passport and Visa Examining' },
      { code: '0986', title: 'Legal Assistance' },
      { code: '0999', title: 'Legal and Kindred Student Trainee' },
    ],
  },
  {
    code: '1000',
    title: 'Information and Arts Group',
    series: [
      { code: '1001', title: 'General Arts and Information' },
      { code: '1008', title: 'Interior Design' },
      { code: '1010', title: 'Exhibits Specialist' },
      { code: '1015', title: 'Museum Specialist' },
      { code: '1016', title: 'Museum Curator' },
      { code: '1020', title: 'Illustrator' },
      { code: '1021', title: 'Office Drafting' },
      { code: '1035', title: 'Public Affairs' },
      { code: '1040', title: 'Language Specialist' },
      { code: '1046', title: 'Language Clerical' },
      { code: '1051', title: 'Museum Curator' },
      { code: '1054', title: 'Museum Specialist and Technician' },
      { code: '1056', title: 'Museum Curator' },
      { code: '1060', title: 'Photography' },
      { code: '1071', title: 'Audiovisual Production' },
      { code: '1082', title: 'Writing and Editing' },
      { code: '1083', title: 'Technical Writing and Editing' },
      { code: '1084', title: 'Visual Information' },
      { code: '1087', title: 'Editorial Assistance' },
      { code: '1099', title: 'Information and Arts Student Trainee' },
    ],
  },
  {
    code: '1100',
    title: 'Business and Industry Group',
    series: [
      { code: '1101', title: 'General Business and Industry' },
      { code: '1102', title: 'Contracting' },
      { code: '1103', title: 'Industrial Property Management' },
      { code: '1104', title: 'Property Disposal' },
      { code: '1105', title: 'Purchasing' },
      { code: '1106', title: 'Procurement Clerical and Technician' },
      { code: '1107', title: 'Property Management' },
      { code: '1109', title: 'General Business and Industry' },
      { code: '1110', title: 'Industrial Property Management' },
      { code: '1125', title: 'Trade Specialist' },
      { code: '1130', title: 'Public Utilities Specialist' },
      { code: '1140', title: 'Trade Specialist' },
      { code: '1144', title: 'Commissary Management' },
      { code: '1145', title: 'Agricultural Program Specialist' },
      { code: '1146', title: 'Agricultural Marketing' },
      { code: '1147', title: 'Agricultural Market Reporting' },
      { code: '1150', title: 'Industrial Specialist' },
      { code: '1152', title: 'Production Control' },
      { code: '1160', title: 'Financial Analysis' },
      { code: '1165', title: 'Loan Specialist' },
      { code: '1169', title: 'Internal Revenue Officer' },
      { code: '1170', title: 'Realty' },
      { code: '1171', title: 'Appraising' },
      { code: '1173', title: 'Housing Management' },
      { code: '1176', title: 'Building Management' },
      { code: '1199', title: 'Business and Industry Student Trainee' },
    ],
  },
  {
    code: '1200',
    title: 'Copyright, Patent, and Trademark Group',
    series: [
      { code: '1202', title: 'Patent Administration' },
      { code: '1203', title: 'Patent Examining' },
      { code: '1204', title: 'Trademark Examining' },
      { code: '1210', title: 'Copyright' },
      { code: '1220', title: 'Patent Administration' },
      { code: '1221', title: 'Patent Adviser' },
      { code: '1222', title: 'Patent Technician' },
      { code: '1223', title: 'Patent Classifying' },
      { code: '1224', title: 'Patent Examining' },
      { code: '1299', title: 'Copyright, Patent, and Trademark Student Trainee' },
    ],
  },
  {
    code: '1300',
    title: 'Physical Sciences Group',
    series: [
      { code: '1301', title: 'General Physical Science' },
      { code: '1306', title: 'Health Physics' },
      { code: '1310', title: 'Physics' },
      { code: '1311', title: 'Physical Science Technician' },
      { code: '1313', title: 'Geophysics' },
      { code: '1315', title: 'Hydrology' },
      { code: '1316', title: 'Hydrologic Technician' },
      { code: '1320', title: 'Chemistry' },
      { code: '1321', title: 'Metallurgy' },
      { code: '1330', title: 'Astronomy and Space Science' },
      { code: '1340', title: 'Meteorology' },
      { code: '1341', title: 'Meteorological Technician' },
      { code: '1350', title: 'Geology' },
      { code: '1360', title: 'Oceanography' },
      { code: '1361', title: 'Navigational Information' },
      { code: '1370', title: 'Cartography' },
      { code: '1371', title: 'Cartographic Technician' },
      { code: '1372', title: 'Geodetic Technician' },
      { code: '1373', title: 'Land Surveying' },
      { code: '1374', title: 'Geodetic Surveying' },
      { code: '1380', title: 'Forest Products Technology' },
      { code: '1382', title: 'Food Technology' },
      { code: '1384', title: 'Textile Technology' },
      { code: '1386', title: 'Photographic Technology' },
      { code: '1397', title: 'Document Analysis' },
      { code: '1399', title: 'Physical Science Student Trainee' },
    ],
  },
  {
    code: '1400',
    title: 'Library and Archives Group',
    series: [
      { code: '1410', title: 'Librarian' },
      { code: '1411', title: 'Library Technician' },
      { code: '1412', title: 'Technical Information Services' },
      { code: '1420', title: 'Archivist' },
      { code: '1421', title: 'Archives Technician' },
      { code: '1499', title: 'Library and Archives Student Trainee' },
    ],
  },
  {
    code: '1500',
    title: 'Mathematics and Statistics Group',
    series: [
      { code: '1501', title: 'General Mathematics and Statistics' },
      { code: '1510', title: 'Actuary' },
      { code: '1515', title: 'Operations Research' },
      { code: '1520', title: 'Mathematics' },
      { code: '1521', title: 'Mathematics Technician' },
      { code: '1529', title: 'Mathematical Statistics' },
      { code: '1530', title: 'Statistics' },
      { code: '1531', title: 'Statistical Assistant' },
      { code: '1540', title: 'Cryptanalysis' },
      { code: '1541', title: 'Cryptography' },
      { code: '1542', title: 'Cryptographic Technician' },
      { code: '1550', title: 'Computer Science' },
      { code: '1599', title: 'Mathematics and Statistics Student Trainee' },
    ],
  },
  {
    code: '1600',
    title: 'Equipment, Facilities, and Services Group',
    series: [
      { code: '1601', title: 'General Facilities and Equipment' },
      { code: '1603', title: 'Equipment, Facilities, and Services Assistance' },
      { code: '1610', title: 'Interior Design' },
      { code: '1640', title: 'Facility Operations Services' },
      { code: '1654', title: 'Printing Services' },
      { code: '1658', title: 'Laundry Operations Services' },
      { code: '1667', title: 'Food Services' },
      { code: '1670', title: 'Equipment Specialist' },
      { code: '1699', title: 'Equipment, Facilities, and Services Student Trainee' },
    ],
  },
  {
    code: '1700',
    title: 'Education Group',
    series: [
      { code: '1701', title: 'General Education and Training' },
      { code: '1702', title: 'Education and Training Technician' },
      { code: '1710', title: 'Education and Vocational Training' },
      { code: '1712', title: 'Training Instruction' },
      { code: '1715', title: 'Vocational Rehabilitation' },
      { code: '1720', title: 'Education Program' },
      { code: '1725', title: 'Public Health Educator' },
      { code: '1730', title: 'Education Research' },
      { code: '1740', title: 'Education Services' },
      { code: '1745', title: 'Education and Training Technician' },
      { code: '1750', title: 'Instructional Systems' },
      { code: '1799', title: 'Education Student Trainee' },
    ],
  },
  {
    code: '1800',
    title: 'Investigation Group',
    series: [
      { code: '1801', title: 'General Inspection, Investigation, Enforcement, and Compliance' },
      { code: '1802', title: 'Compliance Inspection and Support' },
      { code: '1810', title: 'General Investigating' },
      { code: '1811', title: 'Criminal Investigating' },
      { code: '1812', title: 'Game Law Enforcement' },
      { code: '1815', title: 'Air Safety Investigating' },
      { code: '1816', title: 'Immigration Inspection' },
      { code: '1822', title: 'Mine Safety and Health' },
      { code: '1825', title: 'Aircraft Operation' },
      { code: '1831', title: 'Securities Compliance Examining' },
      { code: '1850', title: 'Agricultural Commodity Inspection' },
      { code: '1854', title: 'Alcohol, Tobacco, and Firearms Inspection' },
      { code: '1855', title: 'Customs and Border Protection' },
      { code: '1862', title: 'Consumer Safety Inspection' },
      { code: '1863', title: 'Food Inspection' },
      { code: '1864', title: 'Import Compliance' },
      { code: '1881', title: 'Customs Entry and Liquidating' },
      { code: '1884', title: 'Customs and Border Protection Interdiction' },
      { code: '1889', title: 'Import Specialist' },
      { code: '1890', title: 'Customs and Border Protection' },
      { code: '1894', title: 'Customs and Border Protection' },
      { code: '1895', title: 'Customs and Border Protection' },
      { code: '1896', title: 'Border Patrol Enforcement' },
      { code: '1899', title: 'Investigation Student Trainee' },
    ],
  },
  {
    code: '1900',
    title: 'Quality Assurance, Inspection, and Grading Group',
    series: [
      { code: '1901', title: 'General Inspection, Investigation, Enforcement, and Compliance' },
      { code: '1910', title: 'Quality Assurance' },
      { code: '1980', title: 'Agricultural Commodity Grading' },
      { code: '1999', title: 'Quality Assurance Student Trainee' },
    ],
  },
  {
    code: '2000',
    title: 'Supply Group',
    series: [
      { code: '2001', title: 'General Supply' },
      { code: '2003', title: 'Supply Program Management' },
      { code: '2005', title: 'Supply Clerical and Technician' },
      { code: '2010', title: 'Inventory Management' },
      { code: '2030', title: 'Distribution Facilities and Storage Management' },
      { code: '2032', title: 'Packaging' },
      { code: '2050', title: 'Supply Cataloging' },
      { code: '2091', title: 'Sales Store Clerical' },
      { code: '2099', title: 'Supply Student Trainee' },
    ],
  },
  {
    code: '2100',
    title: 'Transportation Group',
    series: [
      { code: '2101', title: 'Transportation Specialist' },
      { code: '2102', title: 'Transportation Clerk and Assistant' },
      { code: '2110', title: 'Transportation Industry Analysis' },
      { code: '2121', title: 'Railroad Safety' },
      { code: '2123', title: 'Motor Carrier Safety' },
      { code: '2125', title: 'Highway Safety' },
      { code: '2130', title: 'Traffic Management' },
      { code: '2131', title: 'Freight Rate' },
      { code: '2135', title: 'Aircraft Operation' },
      { code: '2139', title: 'Aircraft Operation (Non-Flying)' },
      { code: '2144', title: 'Cargo Scheduling' },
      { code: '2150', title: 'Transportation Operations' },
      { code: '2152', title: 'Aircraft Operation' },
      { code: '2161', title: 'Marine Cargo' },
      { code: '2181', title: 'Aircraft Operation' },
      { code: '2183', title: 'Air Traffic Control' },
      { code: '2185', title: 'Air Traffic Assistance' },
      { code: '2199', title: 'Transportation Student Trainee' },
    ],
  },
  {
    code: '2200',
    title: 'Information Technology Management Group',
    series: [
      { code: '2210', title: 'Information Technology Management' },
      { code: '2299', title: 'Information Technology Management Student Trainee' },
    ],
  },
];

/**
 * Get all occupational groups
 */
export function getOccupationalGroups(): OccupationalGroup[] {
  return OPM_OCCUPATIONAL_GROUPS;
}

/**
 * Get a specific occupational group by code
 */
export function getOccupationalGroupByCode(code: string): OccupationalGroup | undefined {
  return OPM_OCCUPATIONAL_GROUPS.find(group => group.code === code);
}

/**
 * Get all series for a specific occupational group
 */
export function getSeriesByGroupCode(groupCode: string): OccupationalSeries[] {
  const group = getOccupationalGroupByCode(groupCode);
  return group?.series || [];
}

